export enum WeaponCategory {
  Axe = "Axe",
  BowCrossbow = "BowCrossbow",
  FlailHammerMace = "FlailHammerMace",
  SpearPoleArm = "SpearPoleArm",
  SwordDagger = "SwordDagger",
  Other = "Other",
}

export enum WeaponType {
  BattleAxe = "BattleAxe",
  GreatAxe = "GreatAxe",
  HandAxe = "HandAxe",
  Arbalest = "Arbalest",
  Crossbow = "Crossbow",
  CompositeBow = "CompositeBow",
  Longbow = "Longbow",
  Shortbow = "Shortbow",
  Club = "Club",
  Flail = "Flail",
  Mace = "Mace",
  MorningStar = "MorningStar",
  Warhammer = "Warhammer",
  Lance = "Lance",
  Javelin = "Javelin",
  PoleArm = "PoleArm",
  Spear = "Spear",
  Dagger = "Dagger",
  ShortSword = "ShortSword",
  Sword = "Sword",
  TwoHandedSword = "TwoHandedSword",
  Bola = "Bola",
  Dart = "Dart",
  Net = "Net",
  Sling = "Sling",
  Sap = "Sap",
  Staff = "Staff",
  Whip = "Whip",
  GoatBiteRam = "Bite/Ram",
}
